# Generated by Django 3.1.7 on 2021-03-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_created',
            field=models.BooleanField(default=False),
        ),
    ]
