# Generated by Django 3.1.7 on 2021-04-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_user_profile_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hospital_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Hospital Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='worker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='field',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Field/Specialty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='Phone Number'),
        ),
    ]
