# Generated by Django 3.2 on 2021-04-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210404_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
