# Generated by Django 3.1.7 on 2021-04-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_hospitalprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
