# Generated by Django 3.1.7 on 2021-04-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255, null=True)),
                ('job_level', models.CharField(max_length=255, null=True)),
                ('job_description', models.CharField(max_length=255, null=True)),
                ('job_location_hospital', models.CharField(max_length=255, null=True)),
                ('job_location_city', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
