# Generated by Django 3.1.7 on 2021-04-04 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_jobinfo_base_rofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobinfo',
            old_name='base_rofile',
            new_name='base_profile',
        ),
    ]
