# Generated by Django 3.2 on 2021-05-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_jobapplicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicants',
            name='job_status',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
