# Generated by Django 3.2 on 2021-05-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_jobapplicants_job_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerinfo',
            old_name='certifications',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='workerinfo',
            old_name='name',
            new_name='last_name',
        ),
    ]
