# Generated by Django 3.1.7 on 2021-04-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210404_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='job_category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
