# Generated by Django 3.2 on 2021-05-09 05:14

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210509_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerinfo',
            name='cpr_certifications',
        ),
        migrations.AddField(
            model_name='workerinfo',
            name='bls',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
