# Generated by Django 3.1.7 on 2021-04-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_jobinfo_job_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='job_start_month',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
