# Generated by Django 3.2 on 2021-05-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210509_0514'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='workerinfo',
        #     name='bls',
        # ),
        migrations.AddField(
            model_name='workerinfo',
            name='cpr_certifications',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
