# Generated by Django 3.2 on 2021-05-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_workerprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofileinfo',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
