# Generated by Django 3.1.7 on 2021-04-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210412_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='job_hour_end',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='job_hour_start',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
